apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: br4w45jgk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: br4w45jgk-python 
  name: br4w45jgk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: br4w45jgk-python 
