apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: br4w45jgk-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:1852ec3b5c6d7b6e217d8bfbec04b3e7c30207b6@sha256:59749961ff312994119880fedb887a6f49f9fcc34ed5e4df84013fb74393988d
          name: container-image
