apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: br4w45jgk-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:f95e045b4b5745cdadbc411eb6d1547bd241aafd@sha256:6c198c26b26c8b470b40a196ae52bc92611be2112b814ee655837c4dcf0a7932
          name: container-image
